name: build & release packages
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

on:
  schedule:
    - cron: "0 7 1/12 * *"
  workflow_dispatch: {}

jobs:
  build:
    name: "Build: ${{ matrix.script }} (${{ matrix.arch }})"
    permissions:
      actions: read
      security-events: write
      contents: write
    runs-on: ${{ matrix.runs-on }}
    continue-on-error: false
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: x86_64
            platform: linux/amd64
            runs-on: ubuntu-24.04
            script: llvm-mini
          - arch: x86_64
            platform: linux/amd64
            runs-on: ubuntu-24.04
            script: llvm-nano
          - arch: aarch64
            platform: linux/arm64
            runs-on: ubuntu-24.04-arm
            script: llvm-mini
          - arch: aarch64
            platform: linux/arm64
            runs-on: ubuntu-24.04-arm
            script: llvm-nano
          - arch: x86_64
            platform: linux/amd64
            runs-on: ubuntu-24.04
            script: iculess-libxml2
          - arch: aarch64
            platform: linux/arm64
            runs-on: ubuntu-24.04-arm
            script: iculess-libxml2
          - arch: x86_64
            platform: linux/amd64
            runs-on: ubuntu-24.04
            script: iculess-qt6base
          - arch: aarch64
            platform: linux/arm64
            runs-on: ubuntu-24.04-arm
            script: iculess-qt6base
          - arch: x86_64
            platform: linux/amd64
            runs-on: ubuntu-24.04
            script: gtk3-mini
          - arch: aarch64
            platform: linux/arm64
            runs-on: ubuntu-24.04-arm
            script: gtk3-mini
          - arch: x86_64
            platform: linux/amd64
            runs-on: ubuntu-24.04
            script: gtk4-mini
          - arch: aarch64
            platform: linux/arm64
            runs-on: ubuntu-24.04-arm
            script: gtk4-mini
          - arch: x86_64
            platform: linux/amd64
            runs-on: ubuntu-24.04
            script: ffmpeg-mini
          - arch: aarch64
            platform: linux/arm64
            runs-on: ubuntu-24.04-arm
            script: ffmpeg-mini
          - arch: x86_64
            platform: linux/amd64
            runs-on: ubuntu-24.04
            script: opus-nano
          - arch: aarch64
            platform: linux/arm64
            runs-on: ubuntu-24.04-arm
            script: opus-nano
          - arch: x86_64
            platform: linux/amd64
            runs-on: ubuntu-24.04
            script: mesa-mini
          - arch: aarch64
            platform: linux/arm64
            runs-on: ubuntu-24.04-arm
            script: mesa-mini
          - arch: x86_64
            platform: linux/amd64
            runs-on: ubuntu-24.04
            script: mesa-nano
          - arch: aarch64
            platform: linux/arm64
            runs-on: ubuntu-24.04-arm
            script: mesa-nano
          - arch: x86_64
            platform: linux/amd64
            runs-on: ubuntu-24.04
            script: mangohud-pythonless
          - arch: aarch64
            platform: linux/arm64
            runs-on: ubuntu-24.04-arm
            script: mangohud-pythonless
          - arch: x86_64
            platform: linux/amd64
            runs-on: ubuntu-24.04
            script: intel-media-mini
    container:
      image: ghcr.io/pkgforge-dev/archlinux:latest
    env:
      CCACHE_DIR: ${{ github.workspace }}/.ccache
      CCACHE_COMPILERCHECK: content
      CCACHE_SLOPPINESS: time_macros
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          
      - name: set up ccache
        if: ${{ matrix.script != 'iculess-qt6base' }}
        uses: actions/cache@v4
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ${{ runner.os }}-ccache-${{ matrix.script }}-${{ matrix.arch }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-ccache-${{ matrix.script }}-${{ matrix.arch }}-
            
      - name: set up sccache
        if: ${{ matrix.script == 'iculess-qt6base' }}
        uses: actions/cache@v4
        with:
          path: ~/.cache/sccache/
          key: ${{ runner.os }}-sccache-${{ matrix.script }}-${{ matrix.arch }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-sccache-${{ matrix.script }}-${{ matrix.arch }}-
            
      - name: build
        run: |
          sed -i 's/DownloadUser/#DownloadUser/g' /etc/pacman.conf
          pacman -Syu --noconfirm \
            base-devel \
            ccache     \
            clang      \
            cmake      \
            curl       \
            git        \
            ninja      \
            sccache    \
            wget

          export PATH="$PATH:/usr/bin/core_perl"

          sudo sed -i \
            -e 's|DEBUG_CFLAGS="-g"|DEBUG_CFLAGS="-g0"|' \
            -e 's|-fno-omit-frame-pointer|-fomit-frame-pointer|' \
            -e 's|-mno-omit-leaf-frame-pointer||' \
            -e 's|-Wp,-D_FORTIFY_SOURCE=3||' \
            -e 's|-fstack-clash-protection||' \
            -e 's|MAKEFLAGS=.*|MAKEFLAGS="-j$(nproc)"|' \
            -e 's|!ccache|ccache|' \
            -e 's|#MAKEFLAGS|MAKEFLAGS|' /etc/makepkg.conf
          cat /etc/makepkg.conf

          echo "Hacking makepkg to allow building as root in the container..."
          sudo sed -i 's|EUID == 0|EUID == 69|g' /usr/bin/makepkg
          mkdir -p /usr/local/bin
          cp /usr/bin/makepkg /usr/local/bin

          export CC=gcc
          export CXX=g++
          if [ "${{ matrix.script }}" != 'iculess-qt6base' ]; then
            export CMAKE_C_COMPILER_LAUNCHER=ccache
            export CMAKE_CXX_COMPILER_LAUNCHER=ccache
          else
            export CMAKE_C_COMPILER_LAUNCHER=sccache
            export CMAKE_CXX_COMPILER_LAUNCHER=sccache
          fi
          
          chmod +x ./*.sh
          sh ${{ matrix.script }}.sh
          
          if [ "${{ matrix.script }}" != 'iculess-qt6base' ]; then
            ccache -s -v
          else
            sccache --show-stats
          fi

          mkdir ./dist
          sha256sum ./*.pkg.tar.*
          mv ./*.pkg.tar.* ./dist

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ format('{0}-{1}', matrix.script, matrix.arch) }}
          path: "dist"

  release:
    name: "release"
    if: ${{ github.ref_name == 'main' }}
    needs: [build]
    permissions:
      actions: read
      security-events: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: llvm-mini-aarch64

      - uses: actions/download-artifact@v4
        with:
          name: llvm-nano-aarch64

      - uses: actions/download-artifact@v4
        with:
          name: llvm-mini-x86_64

      - uses: actions/download-artifact@v4
        with:
          name: llvm-nano-x86_64

      - uses: actions/download-artifact@v4
        with:
          name: iculess-libxml2-aarch64

      - uses: actions/download-artifact@v4
        with:
          name: iculess-libxml2-x86_64

      - uses: actions/download-artifact@v4
        with:
          name: iculess-qt6base-aarch64

      - uses: actions/download-artifact@v4
        with:
          name: iculess-qt6base-x86_64
      - uses: actions/download-artifact@v4
        with:
          name: gtk3-mini-aarch64

      - uses: actions/download-artifact@v4
        with:
          name: gtk3-mini-x86_64

      - uses: actions/download-artifact@v4
        with:
          name: gtk4-mini-aarch64

      - uses: actions/download-artifact@v4
        with:
          name: gtk4-mini-x86_64

      - uses: actions/download-artifact@v4
        with:
          name: ffmpeg-mini-aarch64

      - uses: actions/download-artifact@v4
        with:
          name: ffmpeg-mini-x86_64

      - uses: actions/download-artifact@v4
        with:
          name: opus-nano-aarch64

      - uses: actions/download-artifact@v4
        with:
          name: opus-nano-x86_64

      - uses: actions/download-artifact@v4
        with:
          name: mesa-mini-aarch64

      - uses: actions/download-artifact@v4
        with:
          name: mesa-mini-x86_64

      - uses: actions/download-artifact@v4
        with:
          name: mesa-nano-aarch64

      - uses: actions/download-artifact@v4
        with:
          name: mesa-nano-x86_64

      - uses: actions/download-artifact@v4
        with:
          name: mangohud-pythonless-aarch64

      - uses: actions/download-artifact@v4
        with:
          name: mangohud-pythonless-x86_64

      - uses: actions/download-artifact@v4
        with:
          name: intel-media-mini-x86_64

      - name: release
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          title: Continuous build
          automatic_release_tag: continuous
          prerelease: false
          draft: false
          files: |
            *.pkg.tar.zst
            *.pkg.tar.xz
          repo_token: ${{ secrets.GITHUB_TOKEN }}
